name: Build & Test .NET Artifacts

on:
  pull_request:
    branches: [develop]

  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      dotnet_version:
        type: string
        default: "8.0.x"
        required: true

jobs:
  checkout-repo:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          cache: false

      - name: Install dependencies
        run: dotnet restore ./src/Presentations/WebApi/WebApi.csproj

      - name: Build
        run: dotnet build ./src/Presentations/WebApi/WebApi.csproj --configuration Release --no-restore

      - name: setup docker build x
        uses: docker/setup-buildx-action@v4

      - name: docker build
        uses: docker/build-push-action@v7
        with:
          context: ./src
          file: ./src/Presentations/WebApi/Dockerfile
          tags: webapi:${{github.sha}}
          load: true
      - name: scan image with trivy
        uses: aquasecurity/trivy-action@v0.36.0
        with: 
          image-ref: wepapi:${{github.sha}}
          format: table
          severity: HIGH, CRITICAL
          ignore-unfixed: ture
          exit-code: 1 

