name: Build & Test .NET Artifacts

on:
  pull_request:
    branches: [develop]

  push:
    branches: [master]

  workflow_dispatch:
    inputs:
      dotnet_version:
        type: string
        default: "8.0.x"
        required: true

jobs:
  checkout-repo:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
          cache: false

      - name: Install dependencies
        run: dotnet restore ./src/Presentations/WebAp/WebApi.csproj

      - name: Build
        run: dotnet build ./src/Presentations/WebAp/WebApi.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test ./src/Presentations/WebAp/WebApi.csproj --configuration Release --verbosity normal